adpn rebalance script / will spit out a short bash script to do the file-system schlepping from one volume to the other.

diff --git a/adpn-do-rebalance b/adpn-do-rebalance
--- a/adpn-do-rebalance
+++ b/adpn-do-rebalance
@@ -62,7 +62,7 @@ rm "${CMDLINETXT}"
 
 EXITCODE=0
 
-V="${_PARAM[verbose]}"
+V="${_LINESWITCH[verbose]}"
 CMD="${_ARGV[1]}"
 
 if [[ ! -z "${_PARAM[version]}" ]] ; then
@@ -98,6 +98,141 @@ case "${CMD}" in
 		EXITCODE="$?"
 		;;
 	
+	"script")
+# @method adpn rebalance script
+# Generate and print out a short bash script to rebalance from one volume to the next.
+# The script that is produced MUST be run by root or a user with sudo privileges.
+# 
+# Usage: 	adpn rebalance script [<AU>] <SOURCE> <DESTINATION> [<OPTIONS>]...
+#
+# AU is the letter code for the AU directory.
+#   Example: to rebalance /cache0/gamma/cache/abc to /cache1, use: adpn rebalance script abc /cache0 /cache1
+#
+# SOURCE is the file system location of the LOCKSS cache volume that HAS the AU.
+#   If AU is NOT specified, use the full path to the AU directory:
+#   Example: adpn rebalance /cache0/gamma/cache/abc /cache1
+#   If AU IS specified, you can abbreviate to  the mount point for the volume:
+#   Example: adpn rebalance abc /cache0 /cache1
+#
+# DESTINATION is the file system location of the LOCKSS cache volume where you WILL MOVE the AU.
+#   Example: adpn rebalance script /cache0/gamma/cache/abc /cache1
+#   to rebalance cache/abc from /cache0 to /cache1
+#
+# @version 2021.0224
+
+		declare -a WORDS
+		WORDS=( "${_ARGV[@]:2}" )
+
+		ARG_OBJECT="${_PARAM[au]}"
+		if [[ -z "${ARG_OBJECT}" ]] ; then
+			ARG_OBJECT="${WORDS[0]}"
+			WORDS=( "${WORDS[@]:1}" )			
+		fi
+		
+		ARG_SRC="${_PARAM[from]}"
+		if [[ -z "${ARG_SRC}" ]] ; then
+			ARG_SRC="${WORDS[0]}"
+			WORDS=( "${WORDS[@]:1}" )
+		fi
+		
+		ARG_DEST="${_PARAM[to]}"
+		if [[ -z "${ARG_DEST}" ]] ; then
+			ARG_DEST="${WORDS[0]}"
+			WORDS=( "${WORDS[@]:1}" )
+			
+			if [[ -z "${ARG_DEST}" ]] ; then
+				ARG_DEST="${ARG_SRC}"
+				ARG_SRC="$( dirname "${ARG_OBJECT}" )"
+				ARG_OBJECT="$( basename "${ARG_OBJECT}" )"
+			fi
+
+		fi
+		
+		
+		SRC_GAMMA=$( "${SCRIPTPATH}" destination --gamma "${ARG_SRC}" )
+		SRC=$( printf "%s/cache/%s" "${SRC_GAMMA}" "${ARG_OBJECT}" )
+		SRC_HIDDEN=$( printf "%s/hide/%s" "${SRC_GAMMA}" "${ARG_OBJECT}" )
+		INTERMEDIATE_GAMMA=$( "${SCRIPTPATH}" destination --gamma "${ARG_DEST}" )
+		INTERMEDIATE_DEST=$( printf "%s/copy/%s" "${INTERMEDIATE_GAMMA}" "${ARG_OBJECT}" )
+		FINAL_DEST=$( "${SCRIPTPATH}" destination "${ARG_DEST}" )
+
+		printf '#!/bin/bash\n'
+		printf '#\n'
+		printf '# generated by %s@%s at %s\n' "${USER}" "$( uname -n )" "$( date )"
+		printf '\n'
+		SCRIPTCMD=$( printf '"%s" sync %s --from="%s" --to="%s"' "${SCRIPTPATH}" "${V}" "${SRC}" "${INTERMEDIATE_DEST}" )
+		SCRIPTPROMPT=$( printf 'read -p %scmd: [%s] Enter OK to continue: %s OK' "'" "${SCRIPTCMD}" "'" )
+		SCRIPTOK='OK="$( printf "%s" "${OK}" | tr "[:upper:]" "[:lower:]")"'
+		printf "%s\n" "${SCRIPTPROMPT}"
+		printf "%s\n" "${SCRIPTOK}"
+		printf "%s %s ; %s\n" 'if [[ "${OK}" == "ok" ]] ; then' "${SCRIPTCMD}" 'fi'
+		
+		SCRIPTCMD=$( printf '"%s" resettle %s --from="%s" --to="%s"' "${SCRIPTPATH}" "${V}" "${INTERMEDIATE_DEST}" "${FINAL_DEST}" )
+		SCRIPTPROMPT=$( printf 'read -p %scmd: [%s] Enter OK to continue: %s OK' "'" "${SCRIPTCMD}" "'" )
+		printf "%s\n" "${SCRIPTPROMPT}"
+		printf "%s\n" "${SCRIPTOK}"
+		printf "%s %s ; %s\n" 'if [[ "${OK}" == "ok" ]] ; then' "${SCRIPTCMD}" 'fi'
+
+		SCRIPTCMD=$( printf '"%s" resettle %s --from="%s" --to="%s"' "${SCRIPTPATH}" "${V}" "${SRC}" "${SRC_HIDDEN}" )
+		SCRIPTPROMPT=$( printf 'read -p %scmd: [%s] Enter OK to continue: %s OK' "'" "${SCRIPTCMD}" "'" )
+		printf "%s\n" "${SCRIPTPROMPT}"
+		printf "%s\n" "${SCRIPTOK}"
+		printf "%s %s ; %s\n" 'if [[ "${OK}" == "ok" ]] ; then' "${SCRIPTCMD}" 'fi'
+ 		
+		;;
+	
+	"sync")
+		"${SCRIPTPATH}" secure ${V} --context="${CMD}" --from="${_PARAM[from]}" --to="${_PARAM[to]}" ; EXITCODE=$?
+		if [[ "${EXITCODE}" -eq 0 ]] ; then
+			IC=""
+			if [[ -n "${V}" ]] ; then
+				IC="--itemize-changes"
+			fi
+			
+			sudo rsync --archive ${IC} "${_PARAM[from]}/" "${_PARAM[to]}"
+			EXITCODE=$?
+		fi
+		;;
+
+	"resettle")
+		"${SCRIPTPATH}" secure ${V} --context="${CMD}" --from="${_PARAM[from]}" --to="${_PARAM[to]}" ; EXITCODE=$?
+		if [[ "${EXITCODE}" -eq 0 ]] ; then
+			sudo mv ${V} "${_PARAM[from]}" "${_PARAM[to]}"
+			EXITCODE=$?
+		fi
+		;;
+
+	"secure")
+		FROM="${_PARAM[from]}"
+		TO="${_PARAM[to]}"
+		
+		if [[ -n "${_PARAM[context]}" ]] ; then
+			CMD="${_PARAM[context]}"
+		fi
+		
+		if [[ -z "${FROM}" ]] ; then
+			printf "[%s %s] REQUIRED: --from=[<SRC>]\n" "${SCRIPT}" "${CMD}" 1>&2
+			EXITCODE=255
+		elif [[ -z "${TO}" ]] ; then
+			printf "[%s %s] REQUIRED: --to=[<DEST>]\n" "${SCRIPT}" "${CMD}" 1>&2
+			EXITCODE=255
+		else
+			# secure the destination directory's existence and permissions, if necessary
+			TO_DIR="$( dirname "${TO}" )"
+			TO_PARENT="$( dirname "${TO_DIR}" )"
+			REF_DIR="${TO_PARENT}/cache"
+
+			if [[ ! -d "${TO_DIR}" ]] ; then
+				sudo mkdir --parents ${V} "${TO_DIR}"
+				if [[ -d "${REF_DIR}" ]] ; then
+					sudo chown ${V} --reference="${REF_DIR}" "${TO_DIR}"
+					sudo chmod ${V} --reference="${REF_DIR}" "${TO_DIR}"
+				fi
+			fi
+			test -d "${TO_DIR}" ; EXITCODE=$?
+		fi
+		;;
+		
 	"destination")
 # @method adpn rebalance destination
 # Generates and displays a directory name for the next available AU directory in a LOCKSS cache volume.
@@ -124,26 +259,33 @@ case "${CMD}" in
 			for DESTINATION in "${DESTINATION_VOLUMES[@]}" ; do
 				CACHE_DIR=$( find "${DESTINATION}" -maxdepth 2 -path '*/gamma/cache' )
 				if [[ -d "${CACHE_DIR}" ]] ; then
-					cd "${CACHE_DIR}"
+					if [[ -z "${_PARAM[gamma]}" ]] ; then
+						cd "${CACHE_DIR}"
 
-					SLUGS=$( find . -maxdepth 1 -type d | xargs -n 1 basename )
-					LONGEST=$( printf "%s" "${SLUGS}" | wc -L )
-					PATTERN=$( printf '^[a-z]{%d}' "${LONGEST}" )
-					LAST_IN_TRANCHE=$( printf "%s" "${SLUGS}" | grep -E "${PATTERN}" | sort -r | head -n 1 )
-					NEXT_IN_TRANCHE=$( "${SCRIPTPATH}" increment --carry "${LAST_IN_TRANCHE}" )
-					
-					if [[ -n "${V}" ]] ; then
-						printf "[%s %s] Last AU cache directory on %s: %s\n" "${SCRIPT}" "${CMD}" "${DESTINATION}" "${LAST_IN_TRANCHE}" 1>&2
-						if [[ -n "${NEXT_IN_TRANCHE}" ]] ; then
-							printf "[%s %s] Next AU cache directory on %s: %s\n" "${SCRIPT}" "${CMD}" "${DESTINATION}" "${NEXT_IN_TRANCHE}" 1>&2
+						SLUGS=$( find . -maxdepth 1 -type d | xargs -n 1 basename )
+						LONGEST=$( printf "%s" "${SLUGS}" | wc -L )
+						PATTERN=$( printf '^[a-z]{%d}' "${LONGEST}" )
+						LAST_IN_TRANCHE=$( printf "%s" "${SLUGS}" | grep -E "${PATTERN}" | sort -r | head -n 1 )
+						NEXT_IN_TRANCHE=$( "${SCRIPTPATH}" increment --carry "${LAST_IN_TRANCHE}" )
+						
+						if [[ -n "${V}" ]] ; then
+							printf "[%s %s] Last AU cache directory on %s: %s\n" "${SCRIPT}" "${CMD}" "${DESTINATION}" "${LAST_IN_TRANCHE}" 1>&2
+							if [[ -n "${NEXT_IN_TRANCHE}" ]] ; then
+								printf "[%s %s] Next AU cache directory on %s: %s\n" "${SCRIPT}" "${CMD}" "${DESTINATION}" "${NEXT_IN_TRANCHE}" 1>&2
+							fi
 						fi
-					fi
+						
+						if [[ -n "${NEXT_IN_TRANCHE}" ]] ; then
+							printf "%s/%s\n" "${CACHE_DIR}" "${NEXT_IN_TRANCHE}"
+						else
+							printf "[%s %s] Could not determine next AU cache directory on %s !\n" "${SCRIPT}" "${CMD}" "${DESTINATION}" 1>&2
+							EXITCODE=1
+						fi
 					
-					if [[ -n "${NEXT_IN_TRANCHE}" ]] ; then
-						printf "%s/%s\n" "${CACHE_DIR}" "${NEXT_IN_TRANCHE}"
 					else
-						printf "[%s %s] Could not determine next AU cache directory on %s !\n" "${SCRIPT}" "${CMD}" "${DESTINATION}" 1>&2
-						EXITCODE=1
+						GAMMA_DIR=$( dirname "${CACHE_DIR}" )
+						printf "%s\n" "${GAMMA_DIR}"
+
 					fi
 				fi
 			done
