adpn confirm / offer a variety of more or less nicely laid-out output formats.

diff --git a/adpn b/adpn
--- a/adpn
+++ b/adpn
@@ -931,7 +931,7 @@ case "${CMD}" in
 			declare -a DST_GREP_TESTS=( )
 			[[ "${_PARAM[added]}" ]] && DST_GREP_OPT+=( "Disk Usage" "Status" "Last Completed Crawl" "Last Crawl" "Last Crawl Result" ) && DST_GREP_TESTS+=( 'Status=~Waiting for [A-Za-z]+' 'LastCompletedPoll=~.*' )
 			[[ "${_PARAM[crawled]}" ]] && DST_GREP_OPT+=( "Disk Usage" "Status" "Last Completed Crawl" "Last Crawl" "Last Crawl Result" ) && DST_GREP_TESTS+=( 'Status=~(Waiting for Poll|[0-9.]*[%] Agreement)' 'LastCompletedCrawl=>0' 'LastCompletedPoll=~.*' )
-			[[ "${_PARAM[preserved]}" ]] && DST_GREP_OPT+=( "Disk Usage" "Status" "Last Completed Crawl" "Last Crawl Result" "Last Completed Poll" "Last Poll Result" )
+			[[ "${_PARAM[preserved]}" ]] && DST_GREP_OPT+=( "Disk Usage" "Status" "Last Completed Crawl" "Last Crawl Result" "Last Completed Poll" "Last Poll Result" ) && DST_GREP_TESTS+=( 'Status=100.00% Agreement' 'LastCompletedCrawl=>0' 'LastCompletedPoll=>0' )
 			[[ "${_PARAM[down]}" ]] && DST_GREP_OPT+=( "Disk Usage" "Status" "Last Completed Crawl" "Last Crawl" "Last Crawl Result" "Available From Publisher" ) && DST_GREP_TESTS+=( "AvailableFromPublisher=No" )
 			[[ "${#_ARGV[@]}" -gt 3 ]] && DST_GREP_OPT+=( "${_ARGV[@]:3}" )
 			[[ "${#DST_GREP_OPT[@]}" -le 1 ]] && DST_GREP_OPT+=( ".*" )
@@ -939,11 +939,13 @@ case "${CMD}" in
 			declare -a DST_GREP=( grep -E "^($( join_by "|" "${DST_GREP_OPT[@]}" ))=" "${DST_OUTPUT}" )
 			declare -a DST_FILTER=( cat - )
 			declare -a DST_OUTPUT=( cat - )
+			declare -a DST_GREP_TESTS_HUMAN_READABLE=()
 			
 			if [[ -n "${_PARAM[preserved]}${_PARAM[added]}${_PARAM[crawled]}${_PARAM[down]}" ]] ; then
 				DST_OUTPUT=( adpn_check_au_status "${_SWITCHES[@]}" )
 				IFS="" ; for TEST in "${DST_GREP_TESTS[@]}" ; do
 					DST_OUTPUT+=( "$( printf -- "--test:%s" "${TEST}" )" )
+					DST_GREP_TESTS_HUMAN_READABLE+=( "$( printf "%s" "${TEST}" | cut --delimiter="=" --field=1 )" )
 				done
 				DST_FILTER=( sed -E -e 's/\t/    /' -e 's/^([^=]+)=(.*)$/\1\t\2/' )
 			elif [[ "${_PARAM[output]}" == "text/tab-separated-values" ]] ; then
@@ -976,7 +978,12 @@ case "${CMD}" in
 			rm "${TMP}"
 		done
 
-		[[ "${EXITCODE}" -gt 0 ]] && adpn_notice "${LINENO}" "adpn_packet2daemonstatustable FAILED." 
+		em_cross_mark="$( printf "\u274C" )"
+		em_heavy_check="$( printf "\u2714" )"
+		
+		GREP_TESTS_HUMAN_READABLE="$( join_by ", " "${DST_GREP_TESTS_HUMAN_READABLE[@]}" )"
+		[[ -z "${QQ}" && "${EXITCODE}" -eq 0 ]] && printf "\n" && adpn_notice "${LINENO}" "%s OK: This AU met all of the test conditions for %s." "${em_heavy_check}" "${GREP_TESTS_HUMAN_READABLE}"
+		[[ "${EXITCODE}" -gt 0 ]] && printf "\n" 1>&2 && adpn_notice "${LINENO}" "%s FAILED: This AU failed to meet one or more of the test conditions (%s)." "${em_cross_mark}" "${GREP_TESTS_HUMAN_READABLE}"
 		;;
 	"commit")
 		TDB_XML=$( adpnprop "props/titlesdb.xml" )
