wordsmithing on script names, etc.

diff --git a/adpn-define-aliases b/adpn-define-aliases
--- a/adpn-define-aliases
+++ b/adpn-define-aliases
@@ -1,4 +1,8 @@
 #!/bin/bash
+#
+# adpn-define-aliases: some basic subroutines used across many of the adpn suite of scripts
+#
+# @version 2019.0807
 
 PATH=${SCRIPTDIR}:${PATH}
 CONFFILE="${SCRIPTDIR}/${SCRIPT}.defaults.conf"
@@ -6,15 +10,28 @@ JSONCONFFILE="${SCRIPTDIR}/adpnet.json"
 
 # adpnparam: retrieve and echo a parameter from the adpnet.json config file
 # example: FOOBAR=$( adpnparam "${KEY}" )
+#
+# @param string key name to retrieve from JSON config file
+# @return int exit code from adpn-json.py (0=success, 1=key not found)
+#
+# @version 2019.0807
 adpnparam() {
 	local key="${1}"
-	REPLY=$(cat "${JSONCONFFILE}" | adpn-json.py --key="${key}")
-	echo "${REPLY}" 
+	if [[ -z "${key}" ]] ; then
+		REPLY=$(cat "${JSONCONFFILE}" | adpn-json.py)
+		JSONEXIT=$?
+	else
+		REPLY=$(cat "${JSONCONFFILE}" | adpn-json.py --key="${key}")
+		JSONEXIT=$?
+	fi
+	printf "%s" "${REPLY}" 
+	return "${JSONEXIT}"
 }
 
 # rawurlencode: Encode a command-line parameter to URL (%hex) style encoding and output
 # example: FOOBAR=$( rawurlencode "${DATA}" )
 # uses code from @Orwellophile at https://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command
+# @version 2019.0807
 rawurlencode() {
   local string="${1}"
   local strlen=${#string}
