adpn preserve - shift notification from an attempt to find e-mail tools over to creating a new issue in Gitlab using adpn gitlab issue --post

diff --git a/adpn-do-gitlab b/adpn-do-gitlab
--- a/adpn-do-gitlab
+++ b/adpn-do-gitlab
@@ -153,19 +153,21 @@ case "${CMD}" in
 	"issue")
 		METHOD=get
 		declare -a ADPN_GITLAB_SW=("--fail")
-		
+
 		if [[ -n "${_PARAM[post]}" ]] ; then
 			METHOD=post
 			[[ -n "${_PARAM[dry-run]}" ]] && ADPN_GITLAB_SW+=("--dry-run")
 			[[ -n "${_PARAM[title]}" ]] && ADPN_GITLAB_SW+=("--data-title=${_PARAM[title]}")
 			[[ -n "${_PARAM[description]}" ]] && ADPN_GITLAB_SW+=("--data-description=${_PARAM[description]}")
-			[[ -n "${_PARAM[labels]}" ]] && ADPN_GITLAB_SW+=("--data-labels=${_PARAM[description]}")
+			[[ -n "${_PARAM[labels]}" ]] && ADPN_GITLAB_SW+=("--data-labels=${_PARAM[labels]}")
 		fi
+		[[ -n "${_PARAM[pipe]}" ]] && ADPN_GITLAB_SW+=("--pipe=${_PARAM[pipe]}")
+		[[ -n "${_PARAM[token]}" ]] & ADPN_GITLAB_SW+=( "--token=${_PARAM[token]}" )
 		
 		API_PATH="/issues"
 		
 		[[ -n "${_PARAM[project]}" ]] && PROJECT="${_PARAM[project]}" || PROJECT="${_ARGV[2]}"
-
+		
 		ISSUE_ASPECT=$( printf "%s" "${PROJECT}" | cut --field=3 --delimiter='#' --only-delimited )
 		ISSUE_ID=$( printf "%s" "${PROJECT}" | cut --field=2 --delimiter='#' --only-delimited )
 		PROJECT=$( printf "%s" "${PROJECT}" | cut --field=1 --delimiter='#' )
@@ -200,7 +202,12 @@ case "${CMD}" in
 		fi
 		
 		F_JSON_OUT=$(mktemp)
-		"${ME}" "${METHOD}" "${ADPN_GITLAB_SW[@]}" "${API_PATH}" ${_LINESWITCH[token]} ${V} ${DBG} > "${F_JSON_OUT}"
+
+		if [[ -n "${_PARAM[pipe]}" ]] ; then
+			printf "%s" "$( cat - )" | "${ME}" "${METHOD}" "${ADPN_GITLAB_SW[@]}" "${API_PATH}" ${V} ${DBG} > "${F_JSON_OUT}"
+		else 
+			"${ME}" "${METHOD}" "${ADPN_GITLAB_SW[@]}" "${API_PATH}" ${V} ${DBG} > "${F_JSON_OUT}"
+		fi
 		EXITCODE="$?"
 
 		if [[ "${_PARAM[output]}" =~ ^(application/)?json$ ]] ; then
@@ -208,6 +215,9 @@ case "${CMD}" in
 		elif [[ "${EXITCODE}" -eq 0 ]] ; then
 			cat "${F_JSON_OUT}" | adpn-json.py --parse "${ADPN_JSON_SW[@]}"
 			EXITCODE="$?"
+		else 
+			printf "[%s] Error from HTTP request (exit code=%d).\n" "${SCRIPT_CMD_NAME}" "${EXITCODE}" 1>&2
+			cat "${F_JSON_OUT}" 1>&2
 		fi
 
 		rm "${F_JSON_OUT}"
@@ -402,6 +412,11 @@ case "${CMD}" in
 				"token"|"context"|"verbose"|"quiet"|"debug"|"dry-run")
 					;;
 				"fail")
+					;;
+				"pipe")
+					PIPED_TEXT="$( cat - )"
+					PIPED_PAIR="$( printf "%s=%s" "${_PARAM[$KEY]}" "${PIPED_TEXT}" )"
+					CURL_SW+=( '--data-urlencode' "${PIPED_PAIR}")
 					;;
 				*)
 					FIELD="${KEY}"
diff --git a/adpn-do-preserve-email b/adpn-do-preserve-email
--- a/adpn-do-preserve-email
+++ b/adpn-do-preserve-email
@@ -10,9 +10,11 @@
 #
 # @version 2019.0807
 
-SCRIPTPATH=$(which $0)
+SCRIPTPATH=$(which "$0")
 SCRIPTDIR=$(dirname "${SCRIPTPATH}")
 SCRIPTNAME=$(basename "${SCRIPTPATH}")
+
+EXITCODE=0
 
 source "${SCRIPTDIR}/adpn-define-aliases"
 
@@ -55,34 +57,95 @@ done
 rm "${CMDLINETXT}"
 
 ##########################################################################################
-### SCRIPT: Get admin e-mail address, subject, and body from config, cmd line or stdin ### ##########################################################################################
+### SCRIPT: Get admin e-mail address, subject, and body from config, cmd line or stdin ###
+##########################################################################################
+
+VV="${_LINESWITCH[verbose]}"
+QQ="${_LINESWITCH[quiet]}"
+V="${_LINESWITCH[verbose]}"
+Q=""
+
+DBG="${_LINESWITCH[debug]}"
+DBGLEVEL="${_PARAM[debug]}"
+if [[ "${DBGLEVEL}" == "debug" ]] ; then
+	DBGLEVEL=1
+fi
+if [[ "${DBGLEVEL}" -gt 1 ]] ; then
+	DBGLEVEL=$(( DBGLEVEL - 1 ))
+	DDBG="--debug=${DBGLEVEL}"
+else
+	DDBG=""
+fi
+
+if [[ -z "${_PARAM[verbose]}" ]] ; then
+	Q="--quiet"
+fi
+if [[ -n "${QQ}" ]] ; then
+	Q="--quiet"
+fi
 
 [ ! -z "${_PARAM[to]}" ] && ADMIN_EMAIL="${_PARAM[to]}" || ADMIN_EMAIL=$(adpnprop preserve/admin-email)
 [ ! -z "${_PARAM[subject]}" ] && SUBJECT_TEXT="${_PARAM[subject]}" || SUBJECT_TEXT="ADPNet Ingest"
 
-ADMIN_EMAIL=$( rawurlencode "${ADMIN_EMAIL}" )
-SUBJECT_TEXT=$( rawurlencode "${SUBJECT_TEXT}" )
-BODY_TEXT=$( rawurlencode "$( cat "${_ARGV[@]}" )" )
+PIPED_TEXT="$( cat "${_ARGV[@]}" )"
+PRETTY_JSON="$( printf "%s" "${PIPED_TEXT}" | adpn-json.py --output=application/json --indent=2 )"
+DEFAULT_REPOSITORY="$( adpnprop gitlab/repository )"
+USER_NAME="$( printf "%s" "${PIPED_TEXT}" | adpn-json.py --key="Staged By" )"
+DIRECTORY="${_PARAM[subdirectory]}"
+
+IFS='' read -r -d '' BODY_TEXT <<EOText
+${USER_NAME} used the \`adpn\` CLI tool to upload files for an ADPNet ingest to the ${LOCATION} staging area, directory: \`${DIRECTORY}\`.
+
+AU meta-data output by \`adpn preserve\` follows:
+
+~~~
+${PIPED_TEXT}
+~~~
+
+Pretty-printed JSON packet:
+
+~~~
+${PRETTY_JSON}
+~~~
+
+This ticket has been created automatically by the \`adpn preserve\` command to notify ADPNet Techs that the AU has been staged and is ready to be tested for ingest, and to provide a place to track the work of adding the new AU to the config server.
+EOText
+
+#ADMIN_EMAIL=$( rawurlencode "${ADMIN_EMAIL}" )
+#SUBJECT_TEXT=$( rawurlencode "${SUBJECT_TEXT}" )
+#BODY_TEXT=$( rawurlencode "${BODY_TEXT}" )
+
+printf "%s" "${BODY_TEXT}" | adpn-do-gitlab issue --post --title="${SUBJECT_TEXT}" --pipe=description --project="${DEFAULT_REPOSITORY}" ${V} ${DDBG}
+EXITCODE="$?"
 
 ##########################################################################################
 ### SCRIPT: Look to see if Outlook.exe is available. #####################################
 ##########################################################################################
 
-OUTLOOK=$( which OUTLOOK.EXE 2> /dev/null )
-if [[ -z "${OUTLOOK}" ]] ; then
-	CYGPATH=$( which cygpath 2> /dev/null )
-	if [[ ! -z "${CYGPATH}" ]] ; then
-		OUTLOOK="$(cygpath "${PROGRAMFILES}\Microsoft Office\root\Office16\OUTLOOK.EXE")"
-		if [[ -z "${OUTLOOK}" || ! -x "${OUTLOOK}" ]] ; then
-			OUTLOOK="$(cygpath "${PROGRAMFILES} (x86)\Microsoft Office\root\Office16\OUTLOOK.EXE")"
-		fi
-	fi
-fi
+#OUTLOOK=$( which OUTLOOK.EXE 2> /dev/null )
+#if [[ -z "${OUTLOOK}" ]] ; then
+#	CYGPATH=$( which cygpath 2> /dev/null )
+#	if [[ ! -z "${CYGPATH}" ]] ; then
+#		OUTLOOK="$(cygpath "${PROGRAMFILES}\Microsoft Office\root\Office16\OUTLOOK.EXE")"
+#		if [[ -z "${OUTLOOK}" || ! -x "${OUTLOOK}" ]] ; then
+#			OUTLOOK="$(cygpath "${PROGRAMFILES} (x86)\Microsoft Office\root\Office16\OUTLOOK.EXE")"
+#		else :
+#			printf "[%s:79] Could not track down Outlook.exe\n" "${SCRIPTNAME}" 1>&2
+#		fi
+#	else :
+#		printf "[%s:82] cygpath is not available\n" "${SCRIPTNAME}" 1>&2
+#	fi
+#fi
 
 ##########################################################################################
 ### SCRIPT: If Outlook.exe is available, use it to spin up an e-mail. ####################
 ##########################################################################################
 
-if [[ ! -z "${OUTLOOK}" && -x "${OUTLOOK}" ]] ; then
-	"${OUTLOOK}" /c ipm.note /m "mailto:${ADMIN_EMAIL}&subject=${SUBJECT_TEXT}&body=${BODY_TEXT}"
-fi
+#if [[ ! -z "${OUTLOOK}" && -x "${OUTLOOK}" ]] ; then
+#	"${OUTLOOK}" /c ipm.note /m "mailto:${ADMIN_EMAIL}&subject=${SUBJECT_TEXT}&body=${BODY_TEXT}"
+#else :
+#	printf "[%s:93] Could not launch Outlook.exe\n" "${SCRIPTNAME}" 1>&2
+#	EXITCODE=1
+#fi
+
+exit "${EXITCODE}"
