adpn rebalance / Fancy workflow uses bagit and symlinks to verify the copy-over and temporarily preserve, then intelligently remove, file system path references.

diff --git a/adpn-do-rebalance b/adpn-do-rebalance
--- a/adpn-do-rebalance
+++ b/adpn-do-rebalance
@@ -63,6 +63,11 @@ rm "${CMDLINETXT}"
 EXITCODE=0
 
 V="${_LINESWITCH[verbose]}"
+Q=""
+if [[ -z "${_PARAM[verbose]}" ]] ; then
+	Q="--quiet"
+fi
+
 CMD="${_ARGV[1]}"
 
 SCRIPT_CMD_NAME="${_PARAM[context]}"
@@ -164,24 +169,28 @@ case "${CMD}" in
 		INTERMEDIATE_DEST=$( printf "%s/copy/%s" "${INTERMEDIATE_GAMMA}" "${ARG_OBJECT}" )
 		FINAL_DEST=$( "${SCRIPTPATH}" destination "${ARG_DEST}" )
 
+		MACHINE="$( uname -n )"
+		TODAY="$( date )"
+		
 		printf '#!/bin/bash\n'
 		printf '#\n'
-		printf '# generated by %s@%s at %s\n' "${USER}" "$( uname -n )" "$( date )"
+		printf '# generated by %s@%s at %s\n' "${USER}" "${MACHINE}" "${TODAY}"
 		printf '\n'
-		SCRIPTCMD=$( printf '"%s" sync %s --from="%s" --to="%s"' "${SCRIPTPATH}" "${V}" "${SRC}" "${INTERMEDIATE_DEST}" )
+		printf 'if [[ "$1" =~ ^--verbose(=.*)?$ ]] ; then V="$1" ; shift ; else V="" ; fi\n'
+		SCRIPTCMD=$( printf '"%s" sync %s ${V} --from="%s" --to="%s"' "${SCRIPTPATH}" "${V}" "${SRC}" "${INTERMEDIATE_DEST}" )
 		SCRIPTPROMPT=$( printf 'read -p %scmd: [%s] Enter OK to continue: %s OK' "'" "${SCRIPTCMD}" "'" )
 		SCRIPTOK='OK="$( printf "%s" "${OK}" | tr "[:upper:]" "[:lower:]")"'
 		printf "%s\n" "${SCRIPTPROMPT}"
 		printf "%s\n" "${SCRIPTOK}"
 		printf "%s %s ; %s\n" 'if [[ "${OK}" == "ok" ]] ; then' "${SCRIPTCMD}" 'fi'
 		
-		SCRIPTCMD=$( printf '"%s" resettle %s --from="%s" --to="%s"' "${SCRIPTPATH}" "${V}" "${INTERMEDIATE_DEST}" "${FINAL_DEST}" )
+		SCRIPTCMD=$( printf '"%s" resettle %s ${V} --from="%s" --to="%s"' "${SCRIPTPATH}" "${V}" "${INTERMEDIATE_DEST}" "${FINAL_DEST}" )
 		SCRIPTPROMPT=$( printf 'read -p %scmd: [%s] Enter OK to continue: %s OK' "'" "${SCRIPTCMD}" "'" )
 		printf "%s\n" "${SCRIPTPROMPT}"
 		printf "%s\n" "${SCRIPTOK}"
 		printf "%s %s ; %s\n" 'if [[ "${OK}" == "ok" ]] ; then' "${SCRIPTCMD}" 'fi'
 
-		SCRIPTCMD=$( printf '"%s" resettle %s --from="%s" --to="%s"' "${SCRIPTPATH}" "${V}" "${SRC}" "${SRC_HIDDEN}" )
+		SCRIPTCMD=$( printf '"%s" resettle %s ${V} --from="%s" --to="%s"' "${SCRIPTPATH}" "${V}" "${SRC}" "${SRC_HIDDEN}" )
 		SCRIPTPROMPT=$( printf 'read -p %scmd: [%s] Enter OK to continue: %s OK' "'" "${SCRIPTCMD}" "'" )
 		printf "%s\n" "${SCRIPTPROMPT}"
 		printf "%s\n" "${SCRIPTOK}"
@@ -249,16 +258,123 @@ org.lockss.poll.v3.enableV3Voter=false
 				IC="--itemize-changes"
 			fi
 			
-			sudo rsync --archive ${IC} "${_PARAM[from]}/" "${_PARAM[to]}"
+			SRC="${_PARAM[from]}"
+			DEST="${_PARAM[to]}"
+			
+			# Bag and tag the source directory.
+			if [[ -d "${SRC}" ]] ; then
+				if [[ ! -d "${SRC}/data" || ! -f "${SRC}/bagit.txt" ]] ; then
+					SRC_LOC="$( readlink -f "${SRC}" )"
+					SRC_SLUG="$( basename "${SRC_LOC}" )"
+					SRC_PARENT="$( dirname "${SRC_LOC}" )"
+					SRC_PARENT_DIR="$( basename "${SRC_PARENT}" )"
+					SRC_GRANDPA="$( dirname "${SRC_PARENT}" )"
+					
+					if [[ "${SRC_PARENT_DIR}" == "cache" ]] ; then
+						SRC_FROM="${SRC_LOC}"
+						SRC_TO="${SRC_GRANDPA}/hide/${SRC_SLUG}"
+						"${SCRIPTPATH}" resettle ${V} --context="${SCRIPT_CMD_NAME}" --from="${SRC_FROM}" --to="${SRC_TO}" ; EXITCODE=$?
+						if [[ "${EXITCODE}" -eq 0 ]] ; then
+							SRC="${SRC_TO}"
+							if [[ ! -e "${SRC_LOC}" ]] ; then
+								sudo ln -s ${V} "${SRC_TO}" "${SRC_LOC%/}" # %/ = remove trailing slash
+							fi
+						fi
+					fi
+					
+					ANCHOR="${PWD}"
+					cd "${SRC}"
+					
+					sudo python "${SCRIPTDIR}/externals/bagit-python/bagit.py" ${Q} "${SRC}" ; EXITCODE=$?
+					if [[ "${EXITCODE}" -eq 0 ]] ; then
+						REF_DIR="${SRC}"
+						DATA_DIR="${SRC}/data"
+						if [[ -d "${DATA_DIR}" ]] ; then
+							sudo chown ${V} --reference="${REF_DIR}" "${DATA_DIR}"
+							sudo chmod ${V} --reference="${REF_DIR}" "${DATA_DIR}"
+						fi
+						
+						if [[ -L "${SRC_LOC%/}" ]] ; then
+							sudo rm ${V} "${SRC_LOC%/}"
+							sudo ln -s ${V} "${SRC_TO}/data" "${SRC_LOC%/}" # %/ = remove trailing slash
+							sudo chown ${V} --no-dereference --reference="${REF_DIR}" "${SRC_LOC%/}"
+						fi
+					fi
+					
+					cd "${ANCHOR}"
+				fi
+			fi
+			
+			# Make the transfer
+			sudo rsync --archive --delete ${IC} "${SRC%/}/" "${DEST}"
 			EXITCODE=$?
+
+			# Validate the transfer, using bagit.py or diff -r
+			if [[ -d "${DEST}" ]] ; then
+				if [[ -d "${DEST}/data" && -f "${DEST}/bagit.txt" ]] ; then
+					ANCHOR="${PWD}"
+					cd "${DEST}"
+					[[ -z "${V}" ]] || printf "[%s] Validating sync using bagit --validate '%s'\n" "${SCRIPT_CMD_NAME}" "${DEST}"
+					python "${SCRIPTDIR}/externals/bagit-python/bagit.py" --validate ${Q} "${DEST}"
+					[[ "${EXITCODE}" -gt 0 ]] || EXITCODE=$?
+					cd "${ANCHOR}"
+				else
+					[[ -z "${V}" ]] || printf "[%s] Validating sync using diff --recursive '%s' '%s'\n" "${SCRIPT_CMD_NAME}" "${SRC}" "${DEST}"
+					diff -q --recursive "${SRC}" "${DEST}"
+					[[ "${EXITCODE}" -gt 0 ]] || EXITCODE=$?
+				fi
+			else
+				printf "[%s] Destination directory not found: %s" "${SCRIPT_CMD_NAME}" "${DEST}" 1>&2
+			fi
+
 		fi
 		;;
 
 	"resettle")
 		"${SCRIPTPATH}" secure ${V} --context="${SCRIPT_CMD_NAME}" --from="${_PARAM[from]}" --to="${_PARAM[to]}" ; EXITCODE=$?
 		if [[ "${EXITCODE}" -eq 0 ]] ; then
-			sudo mv ${V} "${_PARAM[from]}" "${_PARAM[to]}"
-			EXITCODE=$?
+			SRC="${_PARAM[from]}"
+			SRC="${SRC%/}" # take off any trailing slashes
+			DEST="${_PARAM[to]}"
+			DEST="${DEST%/}" # take off any trailing slashes
+
+			# If --from=... is just a symlink that points to (the same place as) --to=..., just delete the symlink.
+			if [[ -L "${SRC}" ]] ; then
+				SRC_ENDPOINT="$( readlink -f "${SRC}" )"
+				SRC_ENDPOINT_BASE="$( basename "${SRC_ENDPOINT}" )"
+				SRC_ENDPOINT_PARENT="$( dirname "${SRC_ENDPOINT}" )"
+				DEST_ENDPOINT="$( readlink -f "${DEST}" )"
+				if [[ "${SRC_ENDPOINT}" == "${DEST_ENDPOINT}" ]] ; then
+					sudo rm ${V} "${SRC}" ; EXITCODE=$?
+				elif [[ "${SRC_ENDPOINT_PARENT}" == "${DEST_ENDPOINT}" ]] ; then
+					if [[ "${SRC_ENDPOINT_BASE}" == "data" ]] ; then
+						sudo rm ${V} "${SRC}" ; EXITCODE=$?
+					fi
+				fi
+			fi
+			
+			POST_LINK=""
+			SRC_PARENT="$( dirname "${SRC}" )"
+			DEST_PARENT="$( dirname "${DEST}" )"
+			if [[ "${SRC_PARENT}" =~ .*/copy$ ]] ; then
+				if [[ "${DEST_PARENT}" =~ .*/cache$ ]] ; then
+					if [[ -d "${SRC}/data" && -f "${SRC}/bagit.txt" ]] ; then
+						POST_LINK="${SRC}/data"
+						SRC="${SRC}/data"
+					fi
+				fi
+			fi
+
+			# If --from=... was not for simple deletion, then move it on over.
+			if [[ -e "${SRC}" ]] ; then
+				sudo mv ${V} "${SRC}" "${DEST}" ; EXITCODE=$?
+			fi
+
+			if [[ -n "${POST_LINK}" ]] ; then
+				DEST_ENDPOINT="$( readlink -f "${DEST}" )"
+				sudo ln -s ${V} "${DEST_ENDPOINT}" "${POST_LINK}"
+			fi
+
 		fi
 		;;
 
