adpn preserve, adpn-do-notify / clean up documentation, output.

diff --git a/adpn-do-notify b/adpn-do-notify
--- a/adpn-do-notify
+++ b/adpn-do-notify
@@ -1,14 +1,11 @@
 #!/bin/bash
 #
-# adpn-do-preserve-email: As part of the ingest process, accept some pipelined JSON data
-# from stdin, and then drop it into an e-mail to the network admin.
+# adpn-do-notify: As part of the ingest process, accept some pipelined JSON data
+# from stdin, and then drop it into an Issue on the Gitlab repository.
 #
-# Usage: <INPUT> | adpn-do-preserve-email --subject="<SUBJECT_LINE>" [--to="<EMAIL>"]
+# Usage: <INPUT> | adpn-do-notify --subject="<SUBJECT_LINE>"
 #
-# - Attempts to find an OUTLOOK.EXE, and if found, uses command-line parameters to spawn
-#   a new e-mail with the specified e-mail address, subject line and body.
-#
-# @version 2019.0807
+# @version 2021.0707
 
 SCRIPTPATH=$(which "$0")
 SCRIPTDIR=$(dirname "${SCRIPTPATH}")
@@ -55,6 +52,11 @@ cat "${SWITCHFILES[@]}" | while IFS="" read -r SWITCH ; do
 done
 
 rm "${CMDLINETXT}"
+
+SCRIPT_CMD_NAME="${_PARAM[context]}"
+if [[ -z "${SCRIPT_CMD_NAME}" ]] ; then
+	SCRIPT_CMD_NAME="${SCRIPTNAME}"
+fi
 
 ##########################################################################################
 ### SCRIPT: Get admin e-mail address, subject, and body from config, cmd line or stdin ###
@@ -122,44 +124,14 @@ printf "%s" "${BODY_TEXT}" | adpn-do-gitlab issue --post --title="${SUBJECT_TEXT
 if [[ "${ADGIP_EXITCODE}" -eq 0 ]] ; then
 	ISSUE_ID="$( cat "${ADPN_GITLAB_POST_JSON}" | adpn-json.py --key="iid" )"
 	ISSUE_URL="$( cat "${ADPN_GITLAB_POST_JSON}" | adpn-json.py --key="web_url" )"
-	printf "[%s] OK: Issue # %d, URL: <%s>\n" "${SCRIPTNAME}" "${ISSUE_ID}" "${ISSUE_URL}"
+	printf "[%s] OK: Issue # %d, URL: <%s>\n" "${SCRIPT_CMD_NAME}" "${ISSUE_ID}" "${ISSUE_URL}"
 else
-	printf "[%s] ERROR: Failed to post new issue to Gitlab [%s]\n" "${SCRIPTNAME}" "${DEFAULT_REPOSITORY}" 1>&2
+	printf "[%s] ERROR: Failed to post new issue to Gitlab [%s]\n" "${SCRIPT_CMD_NAME}" "${DEFAULT_REPOSITORY}" 1>&2
 	cat "${ADPN_GITLAB_POST_JSON}" 1>&2
 fi
 
 rm "${ADPN_GITLAB_POST_JSON}"
 
 EXITCODE="${ADGIP_EXITCODE}"
-
-##########################################################################################
-### SCRIPT: Look to see if Outlook.exe is available. #####################################
-##########################################################################################
-
-#OUTLOOK=$( which OUTLOOK.EXE 2> /dev/null )
-#if [[ -z "${OUTLOOK}" ]] ; then
-#	CYGPATH=$( which cygpath 2> /dev/null )
-#	if [[ ! -z "${CYGPATH}" ]] ; then
-#		OUTLOOK="$(cygpath "${PROGRAMFILES}\Microsoft Office\root\Office16\OUTLOOK.EXE")"
-#		if [[ -z "${OUTLOOK}" || ! -x "${OUTLOOK}" ]] ; then
-#			OUTLOOK="$(cygpath "${PROGRAMFILES} (x86)\Microsoft Office\root\Office16\OUTLOOK.EXE")"
-#		else :
-#			printf "[%s:79] Could not track down Outlook.exe\n" "${SCRIPTNAME}" 1>&2
-#		fi
-#	else :
-#		printf "[%s:82] cygpath is not available\n" "${SCRIPTNAME}" 1>&2
-#	fi
-#fi
-
-##########################################################################################
-### SCRIPT: If Outlook.exe is available, use it to spin up an e-mail. ####################
-##########################################################################################
-
-#if [[ ! -z "${OUTLOOK}" && -x "${OUTLOOK}" ]] ; then
-#	"${OUTLOOK}" /c ipm.note /m "mailto:${ADMIN_EMAIL}&subject=${SUBJECT_TEXT}&body=${BODY_TEXT}"
-#else :
-#	printf "[%s:93] Could not launch Outlook.exe\n" "${SCRIPTNAME}" 1>&2
-#	EXITCODE=1
-#fi
 
 exit "${EXITCODE}"
